version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - common-net
    environment:
      PORT: ${PORT}
      DB_HOST: database
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      CRYPTOCOMPARE_API_URL: ${CRYPTOCOMPARE_API_URL}
  database:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - common-net
    image: "postgres:16"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./migrations/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  common-net: {}